apiVersion: v1
kind: Namespace
metadata:
  name: cafe

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cafe-ingress
  namespace: cafe
  annotations:
    cert-manager.io/cluster-issuer: cafe-prod # issuer for the certificate , we have created it we used this name for on the prodi=ution_issuer.yaml file 
spec:
  ingressClassName: nginx # Ingress class name, if we have more than one ingress we have to mention it which ingress controller need to see this ingress yaml file  
  tls:
  - hosts:
    - cafe.dinextech.com
    secretName: cafe-tls # this name should be unique for each and every ingress.yaml we have creating
  rules:
  - host: cafe.dinextech.com # my cafe.dinextech.com/tea --> will load the cafe page 
    http:
      paths:
      - pathType: Prefix
        path: /tea
        backend:
          service:
            name: tea-svc # tea service name which we created 
            port:
              number: 80
      - pathType: Prefix # --> prefix means in cafe.dinextech.com/ -- after the / coffee will come after that cofee/
        path: /coffee
        backend:
          service:
            name: coffee-svc
            port:
              number: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee
  namespace: cafe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coffee
  template:
    metadata:
      labels:
        app: coffee
    spec:
      containers:
      - name: coffee
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: coffee-svc
  namespace: cafe
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: coffee
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tea
  namespace: cafe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tea
  template:
    metadata:
      labels:
        app: tea
    spec:
      containers:
      - name: tea
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tea-svc
  namespace: cafe
  labels:
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: tea
